sudo: required
language: node_js
node_js: '9'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - ui/node_modules
branches:
  only:
  - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- 
  - export PATH=$HOME/.yarn/bin:$PATH ;
install: ./build.sh
script: ./build.sh
jobs:
  fast_finish: true
  include:
  - stage: deploy
    os: linux
    deploy:
      - provider: releases
        api-key: $GITHUB_AUTH_TOKEN
        name: che-plugin-$(date +'%F-%T')
        file_glob: true
        file: ./assembly/*.tar.gz
        skip_cleanup: true
        on:
          branch: master
